APP_PACKAGE_NAME := $(BUILD_APP_FILE_NAME)_RELEASE

BUILD_VARS := \
    BUILD_ACCOUNT_PASSWORD= \
    BUILD_ACCOUNT_USERNAME= \
    BUILD_ADS_ENABLED=$(PRODUCTION_ADS_ENABLED) \
    BUILD_ADS_LOGGING_ENABLED=false \
    BUILD_ADS_TEST=false \
    BUILD_ANALYTICS_ENABLED=$(PRODUCTION_ANALYTICS_ENABLED) \
    BUILD_ANALYTICS_GA4_MEASUREMENT_ID=$(PRODUCTION_ANALYTICS_GA4_MEASUREMENT_ID) \
    BUILD_ANALYTICS_LOGGING_ENABLED=false \
    BUILD_ANALYTICS_RUDDERSTACK_DATA_PLANE_URL=$(PRODUCTION_ANALYTICS_RUDDERSTACK_DATA_PLANE_URL) \
    BUILD_ANALYTICS_RUDDERSTACK_WRITE_KEY=$(PRODUCTION_ANALYTICS_RUDDERSTACK_WRITE_KEY) \
    BUILD_ANALYTICS_SENTRY_DSN=$(PRODUCTION_ANALYTICS_SENTRY_DSN) \
    BUILD_APP_DEBUG_BANNER_ENABLED=false \
    BUILD_APP_LOGGING_ENABLED=false \
    BUILD_APP_LOGGING_OVERLAY_STARTUP_ENABLED=false \
    BUILD_CONDITIONAL_COMPILATION_FLAGS=$(PRODUCTION_CONDITIONAL_COMPILATION_FLAGS) \
    BUILD_ENVIRONMENT=prod \
    BUILD_NETWORK_LOGGING_ENABLED=false \
    BUILD_OVERRIDE_IS_LOW_MEMORY_HARDWARE= \
    BUILD_OVERRIDE_LOCALE= \
    BUILD_OVERRIDE_SUPPORTS_OPENGL= \
    BUILD_PROXY_IP= \
    BUILD_PROXY_PORT= \
    BUILD_RALE_ENABLED=false

# Set version variables only if not already defined
BUILD_VERSION_MAJOR ?= 0
BUILD_VERSION_MINOR ?= 0
BUILD_VERSION_BUILD ?= 0
BUILD_REPO_HASH ?=
