APP_PACKAGE_NAME := $(BUILD_APP_FILE_NAME)_DEBUG

BUILD_VARS := \
    BUILD_ACCOUNT_PASSWORD=$(DEBUG_ACCOUNT_PASSWORD) \
    BUILD_ACCOUNT_USERNAME=$(DEBUG_ACCOUNT_USERNAME) \
    BUILD_ADS_ENABLED=$(DEBUG_ADS_ENABLED) \
    BUILD_ADS_LOGGING_ENABLED=$(DEBUG_ADS_LOGGING_ENABLED) \
    BUILD_ADS_TEST=$(DEBUG_ADS_TEST_MODE_ENABLED) \
    BUILD_ANALYTICS_ENABLED=$(DEBUG_ANALYTICS_ENABLED) \
    BUILD_ANALYTICS_GA4_MEASUREMENT_ID=$(DEBUG_ANALYTICS_GA4_MEASUREMENT_ID) \
    BUILD_ANALYTICS_LOGGING_ENABLED=$(DEBUG_ANALYTICS_LOGGING_ENABLED) \
    BUILD_ANALYTICS_RUDDERSTACK_DATA_PLANE_URL=$(DEBUG_ANALYTICS_RUDDERSTACK_DATA_PLANE_URL) \
    BUILD_ANALYTICS_RUDDERSTACK_WRITE_KEY=$(DEBUG_ANALYTICS_RUDDERSTACK_WRITE_KEY) \
    BUILD_ANALYTICS_SENTRY_DSN=$(DEBUG_ANALYTICS_SENTRY_DSN) \
    BUILD_APP_DEBUG_BANNER_ENABLED=$(DEBUG_APP_DEBUG_BANNER_ENABLED) \
    BUILD_APP_LOGGING_ENABLED=$(DEBUG_APP_LOGGING_ENABLED) \
    BUILD_APP_LOGGING_OVERLAY_STARTUP_ENABLED=$(DEBUG_APP_LOGGING_OVERLAY_STARTUP_ENABLED) \
    BUILD_CONDITIONAL_COMPILATION_FLAGS=$(DEBUG_CONDITIONAL_COMPILATION_FLAGS) \
    BUILD_ENVIRONMENT=$(DEBUG_ENVIRONMENT) \
    BUILD_NETWORK_LOGGING_ENABLED=$(DEBUG_NETWORK_LOGGING_ENABLED) \
    BUILD_OVERRIDE_IS_LOW_MEMORY_HARDWARE=$(DEBUG_OVERRIDE_IS_LOW_MEMORY_HARDWARE) \
    BUILD_OVERRIDE_LOCALE=$(DEBUG_OVERRIDE_LOCALE) \
    BUILD_OVERRIDE_SUPPORTS_OPENGL=$(DEBUG_OVERRIDE_SUPPORTS_OPENGL) \
    BUILD_PROXY_IP=$(DEBUG_PROXY_IP) \
    BUILD_PROXY_PORT=$(DEBUG_PROXY_PORT) \
    BUILD_RALE_ENABLED=$(DEBUG_RALE_ENABLED)

# Set version variables only if not already defined
BUILD_VERSION_MAJOR ?= 0
BUILD_VERSION_MINOR ?= 0
BUILD_VERSION_BUILD ?= 0
BUILD_REPO_HASH ?=
